// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Price string `json:"price"`
}

type User struct {
	ID        string     `json:"id"`
	Purchases []*Product `json:"purchases"`
}
